### ISSUE TITLE
moafw-msp-st-sn-vkh

### ISSUE THREAD

**Issue by vijaynyaya** [bippisb/bipp-datasets#33]
Dataset Name - msp, Source - Ministry of Agriculture and Farmer's Welfare, Granularity - State, Frequency - Seasonally

**Comment by vijaynyaya** [comment]
It's India level data. 'State Name' and 'State Code' columns need to be removed.

![Dataset Preview](https://github.com/bippisb/bipp-datasets/assets/78458631/137eebe4-8094-4dc9-9a4e-d4f8c4712f94)

**Comment by vijaynyaya** [comment]
We also need to change the SKU.

**Comment by kkhatke** [comment]
SKU and updated dataset are already available in prod-data-2.

SKU : moafw-msp-in-sn-abc

**Comment by kkhatke** [comment]
New one uploaded
