### ISSUE TITLE
moes-imd_cdsp_temperature-pl-mn-aaa

### ISSUE THREAD

**Issue by vijaynyaya** [bippisb/bipp-datasets#38]
Dataset Name - imd_cdsp_temperature, Source - Ministry of Earth Sciences, Granualarity - Other Level, Frequency - Monthly

**Comment by vijaynyaya** [comment]
'Evaluation Parameter' column is redundant.

![Image](https://github.com/bippisb/bipp-datasets/assets/78458631/2fda42e7-a4a4-4db8-be47-20fa6c4207ef)

**Comment by vijaynyaya** [comment]
Names of the stations can also be improved. Currently, they are in snake case.

**Comment by kkhatke** [comment]
Reworking on the dataset.
